# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WallPaperDev' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WallPaperDev
  pod 'CropViewController'
  pod 'SwiftFormat/CLI'
  pod 'SwiftLint'

  target 'WallPaperDevTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WallPaperDevUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
